# Generated by Django 3.1.5 on 2021-01-16 12:20

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='default.jpg', upload_to='userProfile/'),
        ),
    ]
